title: "Kyle Zhang by @kylezgq"
description: "I'm a curious kid obsessed with technology and startups."


header_pages:
  - about.md
  - categories.md
  - contacts.md

style: light

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
