title: 'kylezgq.github.io'
description: "I'm a curious kid obsessed with technology and startups."
url: "https://kylezgq.github.io"


header_pages:
  - about.md
  - categories.md
  - contacts.md


style: light # dark or light (default)
listen_for_clients_preferred_style: true # true or false (default)


plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
